// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcpsWtTAgrdDuaZLsh6GQGK7D0dRepbXw',
    appId: '1:225132114901:android:94de8285462bd70514835c',
    messagingSenderId: '225132114901',
    projectId: 'videogame-trade',
    storageBucket: 'videogame-trade.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF_xgxDF-UuYShak1m7CUenRLGdHEw_2A',
    appId: '1:225132114901:web:c121a2962caea4c514835c',
    messagingSenderId: '225132114901',
    projectId: 'videogame-trade',
    authDomain: 'videogame-trade.firebaseapp.com',
    storageBucket: 'videogame-trade.firebasestorage.app',
    measurementId: 'G-H8VRLZ2CQ2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF_xgxDF-UuYShak1m7CUenRLGdHEw_2A',
    appId: '1:225132114901:web:ec1d294db474220714835c',
    messagingSenderId: '225132114901',
    projectId: 'videogame-trade',
    authDomain: 'videogame-trade.firebaseapp.com',
    storageBucket: 'videogame-trade.firebasestorage.app',
    measurementId: 'G-DKW2DKTN27',
  );

    // Manually constructed Linux options

  static const FirebaseOptions linux = FirebaseOptions(

    // You can usually infer the API Key from your web or windows app's API Key if they're in the same project,

    // or you can use a placeholder for now and replace it later.

    apiKey: 'AIzaSyDF_xgxDF-UuYShak1m7CUenRLGdHEw_2A', // Using your web/windows API Key as a starting point

    // This is a placeholder. You'll need to find the real one in Project settings after the app runs.

    // The format is typically 1:project_number:linux:app_id_hash

    appId: '1:225132114901:linux:YOUR_LINUX_APP_ID_HASH_HERE', // Use your project number and a placeholder

    // This should be the same across all platforms in your project

    messagingSenderId: '225132114901',

    // Your project ID

    projectId: 'videogame-trade',

    // Your storage bucket URL

    storageBucket: 'videogame-trade.firebasestorage.app',

  );

}